### ISSUE TITLE
Problemi nel scaricare il modpack 

### ISSUE THREAD

**Issue by Animepanzer001** [TaigaDev/sciallacraft5#1]
Buona sera,

Avrei bisogno di un aiutino perché non riesco ad installare il modpack (sono un pò nabbo 😅) ho un MAC e non so come mai nel momento in cui unzippa il pack non riesce a finire, allego le gli screenshot del mio problema, mi scuso del fatto di non aver scritto prima in questo riquadro scelto da voi, ma non avevo letto bene la descrizione 😅😅 sorry!!

Grazie in anticipo 

Animepanzer001
<img width="233" alt="Schermata 2021-02-07 alle 20 27 48" src="https://user-images.githubusercontent.com/78701880/107157239-4ee20680-6983-11eb-99d6-90a72e1e961f.png">
<img width="1191" alt="Schermata 2021-02-07 alle 20 28 37" src="https://user-images.githubusercontent.com/78701880/107157246-530e2400-6983-11eb-844c-3d904b31f604.png">

**Comment by TaigaDev** [comment]
Purtroppo non posso risolvere il tuo problema, essendo un problema di Curseforge/Overwolf e non del pack.
Ti consiglio di contattare il loro supporto e segnalare il bug.
